version: 2
updates:
  - package-ecosystem: gomod
    directory: /tools
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(tools)"
      include: scope
    groups:
      go-analysis-tools:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(actions)"
      include: scope
