---
# Hadolint Configuration
# Source: oszuidwest/.github-templates
#
# Copy to: .hadolint.yaml (at repository root)
#
# Documentation: https://github.com/hadolint/hadolint
#
# IMPORTANT: Put ALL ignore rules here, NOT in the workflow file.
# The workflow should reference this config file without duplicating rules.

failure-threshold: warning

ignored:
  # DL3008: Pin versions in apt-get install
  # Often impractical for images that should receive security updates
  - DL3008

  # DL3009: Delete apt-get lists after installing
  # Usually handled in multi-stage builds or combined RUN statements
  - DL3009

trustedRegistries:
  - docker.io
  - ghcr.io
  - gcr.io
  - quay.io

override:
  warning:
    # Warn instead of error for missing version pins in pip
    - DL3013

  info:
    # Info level for MAINTAINER deprecation (use LABEL instead)
    - DL4000
