---
# Docker Quality Workflow Template
# Source: oszuidwest/.github-templates
#
# This workflow lints Dockerfiles, validates YAML, and checks Docker Compose files.
# Copy to: .github/workflows/docker-quality.yml
#
# Required config files:
#   - .hadolint.yaml (at repo root)
#
# Customization:
#   - DOCKERFILE_PATH: Change if Dockerfile is not at root (e.g., "docker/Dockerfile")
#   - Adjust YAML lint rules in the inline config as needed

name: Docker Quality

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  # Customize this if your Dockerfile is in a subdirectory
  DOCKERFILE_PATH: "Dockerfile"

jobs:
  lint:
    name: Lint Docker Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      # Dockerfile linting with Hadolint
      - name: Check for Dockerfile
        id: check_dockerfile
        run: |
          if [ -f "${{ env.DOCKERFILE_PATH }}" ]; then
            echo "has_dockerfile=true" >> $GITHUB_OUTPUT
            echo "Found Dockerfile at ${{ env.DOCKERFILE_PATH }}"
          else
            echo "has_dockerfile=false" >> $GITHUB_OUTPUT
            echo "No Dockerfile found at ${{ env.DOCKERFILE_PATH }}"
          fi

      - name: Hadolint
        if: steps.check_dockerfile.outputs.has_dockerfile == 'true'
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          # Uses .hadolint.yaml from repo root for configuration
          # Do NOT duplicate ignore rules here - put them in .hadolint.yaml

      # YAML linting for configuration files
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_data: |
            extends: default
            rules:
              line-length:
                max: 120
                level: warning
              comments:
                min-spaces-from-content: 1
              truthy:
                allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
              document-start:
                present: false

      # Docker Compose validation
      - name: Check for Docker Compose
        id: check_compose
        run: |
          COMPOSE_FILES=""
          for f in docker-compose.yml docker-compose.yaml compose.yml compose.yaml; do
            if [ -f "$f" ]; then
              COMPOSE_FILES="$COMPOSE_FILES $f"
            fi
          done
          if [ -n "$COMPOSE_FILES" ]; then
            echo "has_compose=true" >> $GITHUB_OUTPUT
            echo "Found compose files:$COMPOSE_FILES"
          else
            echo "has_compose=false" >> $GITHUB_OUTPUT
            echo "No Docker Compose files found"
          fi

      - name: Docker Compose Validation
        if: steps.check_compose.outputs.has_compose == 'true'
        run: |
          # Create minimal .env if it doesn't exist (for validation only)
          if [ ! -f ".env" ]; then
            touch .env
          fi
          # Validate compose file syntax
          if ! docker compose config --quiet 2>&1; then
            echo "::warning::Docker Compose validation failed - may require environment variables"
          fi
