---
# Shell Quality Workflow Template
# Source: oszuidwest/.github-templates
#
# This workflow lints shell scripts using ShellCheck.
# Only triggers when .sh files are modified (path filter).
#
# Copy to: .github/workflows/shell-quality.yml
#
# Note: This workflow is "forward-looking" - it will activate
# automatically when .sh files are added to the repository.

name: Shell Quality

on:
  push:
    branches: [main]
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          check_together: "yes"
          severity: warning
          # Optional: specify specific directories to scan
          # scandir: './scripts'
