---
name: JS Lint

"on":
  push:
    branches: [main]
    paths:
      - '.github/workflows/wp-js-lint.yml'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.css'
      - 'package.json'
      - 'package-lock.json'
      - 'biome.json'
  pull_request:
    paths:
      - '.github/workflows/wp-js-lint.yml'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.css'
      - 'package.json'
      - 'package-lock.json'
      - 'biome.json'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: oszuidwest/.github-templates/.github/workflows/wp-js-ci.yml@v2
    with:
      npm-audit: true
